#!/usr/bin/python
# -*- coding: utf8 -*-

XRGB=[]
XRGB.append('snow')
XRGB.append('gainsboro')
XRGB.append('old lace')
XRGB.append('OldLace')
XRGB.append('linen')
XRGB.append('papaya whip')
XRGB.append('PapayaWhip')
XRGB.append('blanched almond')
XRGB.append('BlanchedAlmond')
XRGB.append('bisque')
XRGB.append('peach puff')
XRGB.append('PeachPuff')
XRGB.append('moccasin')
XRGB.append('cornsilk')
XRGB.append('ivory')
XRGB.append('lemon chiffon')
XRGB.append('LemonChiffon')
XRGB.append('seashell')
XRGB.append('honeydew')
XRGB.append('mint cream')
XRGB.append('MintCream')
XRGB.append('azure')
XRGB.append('alice blue')
XRGB.append('AliceBlue')
XRGB.append('lavender')
XRGB.append('lavender blush')
XRGB.append('LavenderBlush')
XRGB.append('misty rose')
XRGB.append('MistyRose')
XRGB.append('black')
XRGB.append('midnight blue')
XRGB.append('MidnightBlue')
XRGB.append('navy')
XRGB.append('navy blue')
XRGB.append('NavyBlue')
XRGB.append('cornflower blue')
XRGB.append('CornflowerBlue')
XRGB.append('dark slate blue')
XRGB.append('DarkSlateBlue')
XRGB.append('slate blue')
XRGB.append('SlateBlue')
XRGB.append('medium slate blue')
XRGB.append('MediumSlateBlue')
XRGB.append('light slate blue')
XRGB.append('LightSlateBlue')
XRGB.append('medium blue')
XRGB.append('MediumBlue')
XRGB.append('royal blue')
XRGB.append('RoyalBlue')
XRGB.append('blue')
XRGB.append('dodger blue')
XRGB.append('DodgerBlue')
XRGB.append('deep sky blue')
XRGB.append('DeepSkyBlue')
XRGB.append('sky blue')
XRGB.append('SkyBlue')
XRGB.append('light sky blue')
XRGB.append('LightSkyBlue')
XRGB.append('steel blue')
XRGB.append('SteelBlue')
XRGB.append('light steel blue')
XRGB.append('LightSteelBlue')
XRGB.append('light blue')
XRGB.append('LightBlue')
XRGB.append('powder blue')
XRGB.append('PowderBlue')
XRGB.append('pale turquoise')
XRGB.append('PaleTurquoise')
XRGB.append('dark turquoise')
XRGB.append('DarkTurquoise')
XRGB.append('medium turquoise')
XRGB.append('MediumTurquoise')
XRGB.append('turquoise')
XRGB.append('cyan')
XRGB.append('aqua')
XRGB.append('light cyan')
XRGB.append('LightCyan')
XRGB.append('cadet blue')
XRGB.append('CadetBlue')
XRGB.append('medium aquamarine')
XRGB.append('MediumAquamarine')
XRGB.append('aquamarine')
XRGB.append('dark green')
XRGB.append('DarkGreen')
XRGB.append('dark olive green')
XRGB.append('DarkOliveGreen')
XRGB.append('dark sea green')
XRGB.append('DarkSeaGreen')
XRGB.append('sea green')
XRGB.append('SeaGreen')
XRGB.append('medium sea green')
XRGB.append('MediumSeaGreen')
XRGB.append('light sea green')
XRGB.append('LightSeaGreen')
XRGB.append('pale green')
XRGB.append('PaleGreen')
XRGB.append('spring green')
XRGB.append('SpringGreen')
XRGB.append('lawn green')
XRGB.append('LawnGreen')
XRGB.append('green')
XRGB.append('lime')
XRGB.append('chartreuse')
XRGB.append('medium spring green')
XRGB.append('MediumSpringGreen')
XRGB.append('green yellow')
XRGB.append('GreenYellow')
XRGB.append('lime green')
XRGB.append('LimeGreen')
XRGB.append('yellow green')
XRGB.append('YellowGreen')
XRGB.append('forest green')
XRGB.append('ForestGreen')
XRGB.append('olive drab')
XRGB.append('OliveDrab')
XRGB.append('dark khaki')
XRGB.append('DarkKhaki')
XRGB.append('khaki')
XRGB.append('pale goldenrod')
XRGB.append('PaleGoldenrod')
XRGB.append('light goldenrod yellow')
XRGB.append('LightGoldenrodYellow')
XRGB.append('light yellow')
XRGB.append('LightYellow')
XRGB.append('yellow')
XRGB.append('gold')
XRGB.append('light goldenrod')
XRGB.append('LightGoldenrod')
XRGB.append('goldenrod')
XRGB.append('dark goldenrod')
XRGB.append('DarkGoldenrod')
XRGB.append('rosy brown')
XRGB.append('RosyBrown')
XRGB.append('indian red')
XRGB.append('IndianRed')
XRGB.append('saddle brown')
XRGB.append('SaddleBrown')
XRGB.append('sienna')
XRGB.append('peru')
XRGB.append('burlywood')
XRGB.append('beige')
XRGB.append('wheat')
XRGB.append('sandy brown')
XRGB.append('SandyBrown')
XRGB.append('tan')
XRGB.append('chocolate')
XRGB.append('firebrick')
XRGB.append('brown')
XRGB.append('dark salmon')
XRGB.append('DarkSalmon')
XRGB.append('salmon')
XRGB.append('light salmon')
XRGB.append('LightSalmon')
XRGB.append('orange')
XRGB.append('dark orange')
XRGB.append('DarkOrange')
XRGB.append('coral')
XRGB.append('light coral')
XRGB.append('LightCoral')
XRGB.append('tomato')
XRGB.append('orange red')
XRGB.append('OrangeRed')
XRGB.append('red')
XRGB.append('hot pink')
XRGB.append('HotPink')
XRGB.append('deep pink')
XRGB.append('DeepPink')
XRGB.append('pink')
XRGB.append('light pink')
XRGB.append('LightPink')
XRGB.append('pale violet red')
XRGB.append('PaleVioletRed')
XRGB.append('maroon')
XRGB.append('medium violet red')
XRGB.append('MediumVioletRed')
XRGB.append('violet red')
XRGB.append('VioletRed')
XRGB.append('magenta')
XRGB.append('fuchsia')
XRGB.append('violet')
XRGB.append('plum')
XRGB.append('orchid')
XRGB.append('medium orchid')
XRGB.append('MediumOrchid')
XRGB.append('dark orchid')
XRGB.append('DarkOrchid')
XRGB.append('dark violet')
XRGB.append('DarkViolet')
XRGB.append('blue violet')
XRGB.append('BlueViolet')
XRGB.append('purple')
XRGB.append('web purple')
XRGB.append('WebPurple')
XRGB.append('medium purple')
XRGB.append('MediumPurple')
XRGB.append('thistle')
XRGB.append('snow1')
XRGB.append('snow2')
XRGB.append('snow3')
XRGB.append('snow4')
XRGB.append('seashell1')
XRGB.append('seashell2')
XRGB.append('seashell3')
XRGB.append('seashell4')
XRGB.append('bisque1')
XRGB.append('bisque2')
XRGB.append('bisque3')
XRGB.append('bisque4')
XRGB.append('PeachPuff1')
XRGB.append('PeachPuff2')
XRGB.append('PeachPuff3')
XRGB.append('PeachPuff4')
XRGB.append('LemonChiffon1')
XRGB.append('LemonChiffon2')
XRGB.append('LemonChiffon3')
XRGB.append('LemonChiffon4')
XRGB.append('cornsilk1')
XRGB.append('cornsilk2')
XRGB.append('cornsilk3')
XRGB.append('cornsilk4')
XRGB.append('ivory1')
XRGB.append('ivory2')
XRGB.append('ivory3')
XRGB.append('ivory4')
XRGB.append('honeydew1')
XRGB.append('honeydew2')
XRGB.append('honeydew3')
XRGB.append('honeydew4')
XRGB.append('LavenderBlush1')
XRGB.append('LavenderBlush2')
XRGB.append('LavenderBlush3')
XRGB.append('LavenderBlush4')
XRGB.append('MistyRose1')
XRGB.append('MistyRose2')
XRGB.append('MistyRose3')
XRGB.append('MistyRose4')
XRGB.append('azure1')
XRGB.append('azure2')
XRGB.append('azure3')
XRGB.append('azure4')
XRGB.append('SlateBlue1')
XRGB.append('SlateBlue2')
XRGB.append('SlateBlue3')
XRGB.append('SlateBlue4')
XRGB.append('RoyalBlue1')
XRGB.append('RoyalBlue2')
XRGB.append('RoyalBlue3')
XRGB.append('RoyalBlue4')
XRGB.append('blue1')
XRGB.append('blue2')
XRGB.append('blue3')
XRGB.append('blue4')
XRGB.append('DodgerBlue1')
XRGB.append('DodgerBlue2')
XRGB.append('DodgerBlue3')
XRGB.append('DodgerBlue4')
XRGB.append('SteelBlue1')
XRGB.append('SteelBlue2')
XRGB.append('SteelBlue3')
XRGB.append('SteelBlue4')
XRGB.append('DeepSkyBlue1')
XRGB.append('DeepSkyBlue2')
XRGB.append('DeepSkyBlue3')
XRGB.append('DeepSkyBlue4')
XRGB.append('SkyBlue1')
XRGB.append('SkyBlue2')
XRGB.append('SkyBlue3')
XRGB.append('SkyBlue4')
XRGB.append('LightSkyBlue1')
XRGB.append('LightSkyBlue2')
XRGB.append('LightSkyBlue3')
XRGB.append('LightSkyBlue4')
XRGB.append('LightSteelBlue1')
XRGB.append('LightSteelBlue2')
XRGB.append('LightSteelBlue3')
XRGB.append('LightSteelBlue4')
XRGB.append('LightBlue1')
XRGB.append('LightBlue2')
XRGB.append('LightBlue3')
XRGB.append('LightBlue4')
XRGB.append('LightCyan1')
XRGB.append('LightCyan2')
XRGB.append('LightCyan3')
XRGB.append('LightCyan4')
XRGB.append('PaleTurquoise1')
XRGB.append('PaleTurquoise2')
XRGB.append('PaleTurquoise3')
XRGB.append('PaleTurquoise4')
XRGB.append('CadetBlue1')
XRGB.append('CadetBlue2')
XRGB.append('CadetBlue3')
XRGB.append('CadetBlue4')
XRGB.append('turquoise1')
XRGB.append('turquoise2')
XRGB.append('turquoise3')
XRGB.append('turquoise4')
XRGB.append('cyan1')
XRGB.append('cyan2')
XRGB.append('cyan3')
XRGB.append('cyan4')
XRGB.append('aquamarine1')
XRGB.append('aquamarine2')
XRGB.append('aquamarine3')
XRGB.append('aquamarine4')
XRGB.append('DarkSeaGreen1')
XRGB.append('DarkSeaGreen2')
XRGB.append('DarkSeaGreen3')
XRGB.append('DarkSeaGreen4')
XRGB.append('SeaGreen1')
XRGB.append('SeaGreen2')
XRGB.append('SeaGreen3')
XRGB.append('PaleGreen1')
XRGB.append('PaleGreen2')
XRGB.append('PaleGreen3')
XRGB.append('SpringGreen1')
XRGB.append('SpringGreen2')
XRGB.append('SpringGreen3')
XRGB.append('DarkOliveGreen1')
XRGB.append('DarkOliveGreen2')
XRGB.append('khaki1')
XRGB.append('khaki2')
XRGB.append('khaki3')
XRGB.append('LightGoldenrod1')
XRGB.append('LightGoldenrod2')
XRGB.append('LightGoldenrod3')
XRGB.append('LightYellow1')
XRGB.append('LightYellow2')
XRGB.append('LightYellow3')
XRGB.append('LightYellow4')
XRGB.append('RosyBrown1')
XRGB.append('RosyBrown2')
XRGB.append('RosyBrown3')
XRGB.append('RosyBrown4')
XRGB.append('IndianRed1')
XRGB.append('burlywood1')
XRGB.append('burlywood2')
XRGB.append('burlywood3')
XRGB.append('wheat1')
XRGB.append('wheat2')
XRGB.append('wheat3')
XRGB.append('wheat4')
XRGB.append('salmon1')
XRGB.append('LightSalmon1')
XRGB.append('LightSalmon2')
XRGB.append('DeepPink1')
XRGB.append('DeepPink2')
XRGB.append('DeepPink3')
XRGB.append('HotPink1')
XRGB.append('HotPink2')
XRGB.append('HotPink3')
XRGB.append('HotPink4')
XRGB.append('pink1')
XRGB.append('pink2')
XRGB.append('pink3')
XRGB.append('pink4')
XRGB.append('LightPink1')
XRGB.append('LightPink2')
XRGB.append('LightPink3')
XRGB.append('LightPink4')
XRGB.append('PaleVioletRed1')
XRGB.append('PaleVioletRed2')
XRGB.append('PaleVioletRed3')
XRGB.append('maroon1')
XRGB.append('maroon2')
XRGB.append('maroon3')
XRGB.append('VioletRed1')
XRGB.append('VioletRed2')
XRGB.append('VioletRed3')
XRGB.append('magenta1')
XRGB.append('magenta2')
XRGB.append('magenta3')
XRGB.append('magenta4')
XRGB.append('orchid1')
XRGB.append('orchid2')
XRGB.append('orchid3')
XRGB.append('orchid4')
XRGB.append('plum1')
XRGB.append('plum2')
XRGB.append('plum3')
XRGB.append('plum4')
XRGB.append('MediumOrchid1')
XRGB.append('MediumOrchid2')
XRGB.append('MediumOrchid3')
XRGB.append('MediumOrchid4')
XRGB.append('DarkOrchid1')
XRGB.append('DarkOrchid2')
XRGB.append('DarkOrchid3')
XRGB.append('DarkOrchid4')
XRGB.append('purple1')
XRGB.append('purple2')
XRGB.append('purple3')
XRGB.append('purple4')
XRGB.append('MediumPurple1')
XRGB.append('MediumPurple2')
XRGB.append('MediumPurple3')
XRGB.append('MediumPurple4')
XRGB.append('thistle1')
XRGB.append('thistle2')
XRGB.append('thistle3')
XRGB.append('thistle4')
XRGB.append('dark blue')
XRGB.append('DarkBlue')
XRGB.append('dark cyan')
XRGB.append('DarkCyan')
XRGB.append('dark magenta')
XRGB.append('DarkMagenta')
XRGB.append('dark red')
XRGB.append('DarkRed')
XRGB.append('light green')
XRGB.append('LightGreen')
XRGB.append('crimson')
XRGB.append('indigo')
XRGB.append('olive')
XRGB.append('rebecca purple')
XRGB.append('RebeccaPurple')
XRGB.append('silver')
XRGB.append('teal')
